### ISSUE TITLE
Display Error on MMM-BMW-CC

### ISSUE THREAD

**Issue by contactmike1** [mykle1/MMM-BMW-CC#1]
Hello,

I noticed this module didn't display correctly out of the box. Note that instead of displaying the day "Fri", it says "undefined". 
Also, the last day of the forecast "Thu" is missing the icon.  

![shot3](https://user-images.githubusercontent.com/75455469/101848563-659ee500-3b1b-11eb-8c1a-3af1ecd9ba6a.png)

I did a little troubleshooting and here are my insights: 

The variable 'today'  has the wrong scope:
```
      // if the data date is the same as today then today's forecast says "today" See line 120
        if (moment(forecast[0].observation_time.value).format('ddd') == moment().format('ddd')){
       var today = "Today";
        }
```
Since the variable is created inside the IF statement, its scope only exists inside the IF statement. So that is why the screen displays "undefined" because the variable isn't accessible outside the IF statement.  I simply defined it outside the IF statement to get it to display. 

```
var today = moment(forecast[0].observation_time.value).format('ddd') ;
     
     // if the data date is the same as today then today's forecast says "today" See line 120
        if (moment(forecast[0].observation_time.value).format('ddd') == moment().format('ddd')){
       today = "Today";
        }
```
That should solve the first item.  

For the second item, I added some debugging to print the icon path so I could see what was breaking. 
![shot4](https://user-images.githubusercontent.com/75455469/101848574-6f284d00-3b1b-11eb-8099-f4335bf8a37b.png)

You can see that the weather API returned `mostly_clear`, but the icon is named `mostlyclear.png` in the folder.  So you just need to update the icon name to `mostly_clear.png`. Mine worked after doing that. I don't know if other icons have similar naming issues or not, but I'll try to remember to report them if I come across any others. I looked at the names in the icon folder, and it does seem inconsistent when there is a "_" and when it's omitted. I'm not sure if the actual weather API is this way, or perhaps you can just look in the icon folder and know which ones need updating.  

Last question, I noticed that this module seems to break my touchscreen when using MMM-page-indicator. Normally, I have MMM-page-indicator on the bottom bar, and it works fine on the bottom bar until I enable MMM-BMW-CC on the bottom_bar. Once MMM-BMW-CC is enabled, the touchscreen functionality stops working, and I can no longer touch the "circles" to change pages. The page display indicators show up as expected, but I can no longer touch them. The temporary workaround is I moved the MMM-page-indicator to the upper left hand corner (as you can see in the screenshots) and touch works there, but it's almost like MMM-BMW-CC has an invisible hit area that covers up the page controls, and they can't be used anymore.  Any thoughts about how the module might break touchscreen control?

Another fascinating thing: on my second page, I have MMM-Climacell-Hourly on the bottom-bar with MMM-page-indicator on the bottom-bar, and they work flawlessly together. The touch works fine, and MMM-Climacell-Hourly doesn't interfere with the ability to touch to select a page. Is there a significant difference in how climacell and bmw achieve their output? For some reason, there seems to be a difference for touchscreen controls since BMW breaks touchscreen and climacell does not.
![shot6](https://user-images.githubusercontent.com/75455469/101850017-8288e780-3b1e-11eb-9e50-6e8a7bd07522.png)

EDIT: Upon testing this again when getting the data and screenshots for this post, BMW and MMM-page-indicator are now working together nicely with both in the bottom bar. So I am not sure what the difference is, but I will continue to monitor. 

EDIT2: Well sometimes touch control does stop working. Maybe I am too quick to blame the module and it's something else. I have found that if I execute (touch) page controls to change pages before BMW finishes loading everything, touch works fine, even after returning to the homepage and letting it sit. If I let the BMW module fully load up, sometimes touch will continue working, and other times, it's just completely dead. So I'm not sure 100% if it's an issue with the module or the mirror in general, but it seems to only happen if MMM-page-indicator AND something else are in the bottom_bar together. And climacell and bmw are the only modules i've tested in the bottom_bar.

**Comment by cowboysdude** [comment]
Pull request sent, fixed.

**Comment by mykle1** [comment]
Yo CBD!

Thanks for taking the initiative and contributing. Lots of people want stuff done but very few actually volunteer to help. In your case, you just sent me the PR with the work already done. I really appreciate that. It's hard to keep up as you well know.

Peace!

**Comment by mykle1** [comment]
Ok, so, the updated module now works with the new api keys. Sorry about the delay. I was using an older v3 api key. It still works but will be closed soon. The new api keys work with the new version 4 of the api itself. This module has been updated to make use of the new v4 api.

My apologies
